server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:        
        registration:
          google:
            client-id: 290927198833-2nil12dpbuq2tfmi4u2rmj5ci4fgg3q6.apps.googleusercontent.com
            client-secret: mP842ZoaGp9f8vO99d6CVzUF
          github:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          facebook:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          okta:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs 
          okta:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
            
#security:
#  oauth2:
#    client:
#      google:
#        scopes:  openid,email,profile
#        redirectUri: http://localhost:8080/oauth2/authorize/code/google
#        authorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#        tokenUri: https://www.googleapis.com/oauth2/v4/token
#        userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#        jwkSetUri: https://www.googleapis.com/oauth2/v3/certs
#        client-id: 290927198833-2nil12dpbuq2tfmi4u2rmj5ci4fgg3q6.apps.googleusercontent.com
#        client-secret: mP842ZoaGp9f8vO99d6CVzUF